name: CI PHPUnit

on: [push]

jobs:
  ci-phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1.2"
          extensions: curl , zlib , intl , ctype , phar , pcov , xdebug , pcntl , libxml , xml , soap , posix , mbstring , dom , tokenizer , xmlwriter , json , zip
      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
#          php_extensions: curl zlib intl ctype phar pcov xdebug pcntl libxml xml soap posix mbstring dom tokenizer xmlwriter json zip
          args: --testdox
